remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme

title: Highcharts Sonification Studio Resource Page
description: [A short description of your site's purpose]

github:
  repository_url: https://github.com/awalmer/GitHub-Page-Mock-Up
  owner_name: awalmer